In [1]:
import numpy as np
import pandas as pd
import os
import cv2
import glob
# import random
# import gc
# import matplotlib.pyplot as plt 
# import seaborn as snb; snb.set()

# #Model Libraries
# from keras import metrics
# from tensorflow.keras import Input,Model
# from tensorflow.keras.layers import Dense
# from tensorflow.keras.utils import plot_model, to_categorical
# from tensorflow.keras.callbacks import EarlyStopping, Callback


In [10]:
#Reading the files and creating the labels for the test data set
X, count_labels,long, i, j  = [], [], [], 0, 0

directories = ["AFAD-Lite/18/111","AFAD-Lite/18/112","AFAD-Lite/19/111","AFAD-Lite/19/112","AFAD-Lite/20/111","AFAD-Lite/20/112",
              "AFAD-Lite/21/111","AFAD-Lite/21/112","AFAD-Lite/22/111","AFAD-Lite/22/112","AFAD-Lite/23/111","AFAD-Lite/23/112",
              "AFAD-Lite/24/111","AFAD-Lite/24/112","AFAD-Lite/25/111","AFAD-Lite/25/112","AFAD-Lite/26/111","AFAD-Lite/26/112",
              "AFAD-Lite/27/111","AFAD-Lite/27/112","AFAD-Lite/28/111","AFAD-Lite/28/112","AFAD-Lite/29/111","AFAD-Lite/29/112",
              "AFAD-Lite/30/111","AFAD-Lite/30/112","AFAD-Lite/31/111","AFAD-Lite/31/112","AFAD-Lite/32/111","AFAD-Lite/32/112",
              "AFAD-Lite/33/111","AFAD-Lite/33/112","AFAD-Lite/34/111","AFAD-Lite/34/112","AFAD-Lite/35/111","AFAD-Lite/35/112",
              "AFAD-Lite/36/111","AFAD-Lite/36/112","AFAD-Lite/37/111","AFAD-Lite/37/112","AFAD-Lite/38/111","AFAD-Lite/38/112",
              "AFAD-Lite/39/111","AFAD-Lite/39/112"]
for test_dir in directories:
    j=j+1
    for root, dirs, files in os.walk(test_dir):
        if i==0:
            names=dirs
        else:
            count_labels.append(len(files))
        i=i+1
        for y in glob.glob(os.path.join(root, '*.jpg')):
            img = cv2.imread(y) 
            img.resize((200, 200))
            RGB_img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) 
            X.append(RGB_img) 
        long.append(len(files))
    print("Directorio ",j)
    

edades = np.repeat(np.arange(18,40),np.repeat(2,22))
y = np.repeat(edades,long)
X = np.array(X)

Directorio  1
Directorio  2
Directorio  3
Directorio  4
Directorio  5
Directorio  6
Directorio  7
Directorio  8
Directorio  9
Directorio  10
Directorio  11
Directorio  12
Directorio  13
Directorio  14
Directorio  15
Directorio  16
Directorio  17
Directorio  18
Directorio  19
Directorio  20
Directorio  21
Directorio  22
Directorio  23
Directorio  24
Directorio  25
Directorio  26
Directorio  27
Directorio  28
Directorio  29
Directorio  30
Directorio  31
Directorio  32
Directorio  33
Directorio  34
Directorio  35
Directorio  36
Directorio  37
Directorio  38
Directorio  39
Directorio  40
Directorio  41
Directorio  42
Directorio  43
Directorio  44


In [45]:
edades = np.repeat(np.arange(18,40,2),np.repeat(4,11))
#y = np.repeat(edades,long)
#np.save("y.npi",y)
edades

array([18, 18, 18, 18, 20, 20, 20, 20, 22, 22, 22, 22, 24, 24, 24, 24, 26,
       26, 26, 26, 28, 28, 28, 28, 30, 30, 30, 30, 32, 32, 32, 32, 34, 34,
       34, 34, 36, 36, 36, 36, 38, 38, 38, 38])

In [43]:
np.arange(18,40,3)

array([18, 21, 24, 27, 30, 33, 36, 39])

In [40]:
np.array([18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

array([18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [29]:
#np.save("X.npy",X)
#np.save("y.npy",y)

In [31]:
# Sampleando los conjuntos de datos para menor demanda de recursos

import random
random.seed(42)

n_sample = 30000
sample = random.sample(range(0, len(X)), n_sample)
train_sample = sample[0:20000]
test_sample = sample[20000:n_sample]
X_train = X[train_sample]
X_test = X[test_sample]
y_train = y[train_sample]
y_test = y[test_sample]

#One hot encoding
y_test=pd.get_dummies(y_test)
y_train=pd.get_dummies(y_train)

print(np.shape(X_train),np.shape(y_train),np.shape(X_test),np.shape(y_test))

(20000, 200, 200, 3) (20000,) (10000, 200, 200, 3) (10000,)


In [33]:
#Model Libraries
#from keras import metrics
#from tensorflow.keras import Input,Model
from tensorflow.keras.models import load_model
#from tensorflow.keras.layers import Dense
#from tensorflow.keras.utils import plot_model, to_categorical
#from tensorflow.keras.callbacks import EarlyStopping, Callback

load_model("c3ae_imdb_v89.h5")

ValueError: The last dimension of the inputs to `Dense` should be defined. Found `None`.

In [164]:
#To clear some Memory 
gc.collect()

# Neural Net of 3 
input_shape = Input(shape = (30000,))
x = Dense(1000, activation = "relu")(input_shape) 
x = Dense(1000, activation = "relu")(x)
x = Dense(1000, activation = "relu")(x)
x = Dense(1000, activation = "relu")(x) 
x = Dense(1000, activation = "relu")(x)
output = Dense(131, activation ="softmax")(x)

#se crea el modelo
model = Model(input_shape, output)
model.summary()


In [25]:
y[[train_sample]]

C:\Users\javie\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


20000

In [27]:
np.shape(X[[1,3,5,6]])

(4, 200, 200, 3)